blog_app/config/routes.rb
TestApp::Application.routes.draw do
  resources :posts
  root 'welcome#index'
end

  

  #   end

blog_app/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
 
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def index
  @posts = Post.all
  end

  private
    def post_params
      params.require(:post).permit(:title, :text)
    end
end

blog_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog_app/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_app/app/helpers/posts_helper.rb
module PostsHelper
end

blog_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog_app/app/views/posts/index.html.erb
<h1>Listing posts</h1>
 
<%= link_to 'Create a new post', new_post_path %>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back', posts_path %>

blog_app/app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', posts_path %>

blog_app/app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>


<%= link_to 'Back', posts_path %>

blog_app/app/views/welcome/index.html.erb
<h1>Hello rails!</h1>
<%= link_to "My Blog", controller: "posts" %>